// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOFxHFrqZIV4iAQdv4kvo-wz67dnIHBb8',
    appId: '1:256908577861:web:6859a22d0c39c3efb0e72c',
    messagingSenderId: '256908577861',
    projectId: 'taskino-c171f',
    authDomain: 'taskino-c171f.firebaseapp.com',
    storageBucket: 'taskino-c171f.firebasestorage.app',
    measurementId: 'G-FJV79T8BEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgUpBPArPcrWhYrU35u8f7Wd2it60DnHo',
    appId: '1:256908577861:android:32b3288f3817e2feb0e72c',
    messagingSenderId: '256908577861',
    projectId: 'taskino-c171f',
    storageBucket: 'taskino-c171f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnqJMT_mei45nh_K153a0UUuFXdLUYUbU',
    appId: '1:256908577861:ios:167833c0a39417fcb0e72c',
    messagingSenderId: '256908577861',
    projectId: 'taskino-c171f',
    storageBucket: 'taskino-c171f.firebasestorage.app',
    iosBundleId: 'com.example.taskino',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnqJMT_mei45nh_K153a0UUuFXdLUYUbU',
    appId: '1:256908577861:ios:167833c0a39417fcb0e72c',
    messagingSenderId: '256908577861',
    projectId: 'taskino-c171f',
    storageBucket: 'taskino-c171f.firebasestorage.app',
    iosBundleId: 'com.example.taskino',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOFxHFrqZIV4iAQdv4kvo-wz67dnIHBb8',
    appId: '1:256908577861:web:548aeee3b714ad52b0e72c',
    messagingSenderId: '256908577861',
    projectId: 'taskino-c171f',
    authDomain: 'taskino-c171f.firebaseapp.com',
    storageBucket: 'taskino-c171f.firebasestorage.app',
    measurementId: 'G-2RRH59TMFD',
  );

}